### ISSUE TITLE
Sudden drop in audio toward bottom end of slider range

### ISSUE THREAD

**Issue by y0mo1337** [Narfjones/CTRLDeck-Python#3]
When lowering volume toward the bottom of the slider, the audio will suddenly drop out instead of following the same linear response as the rest of the range. Note that this does not happen at the top of the range, only at the bottom. In Windows Volume Mixer, you'll notice the number going immediately from 3 -> 0, rather than 3 -> 2 -> 1 -> 0.

**Comment by ngc6027** [comment]
@Narfjones says this is expected due to something on the Arduino side. Will take a look later on.

**Comment by Narfjones** [comment]
This is now fixed. Instead of setting volume to 0 when the input float value is below .02 it now sets volume to 0 if the input value is == 0. Without this statement, the volume will never go below 2-3. The faster you move the slider, the higher the volume is when it gets stuck.
